CREATE TABLE company (
    unique_id VARCHAR PRIMARY KEY,
    raw_json JSON,
    account_number NUMERIC NULL,
    address_full_text VARCHAR NULL,
    address_line_1 VARCHAR NULL,
    address_line_2 VARCHAR NULL,
    amendments_resolution VARCHAR NULL,
    article_of_incorporation VARCHAR NULL,
    articles_of_organization_article_of_corporation VARCHAR NULL,
    authorized_signor_resolution VARCHAR NULL,
    bank_address VARCHAR NULL,
    bank_forcreditto VARCHAR NULL,
    bank_name VARCHAR NULL,
    bank_specialinstructions VARCHAR NULL,
    borrower_entity VARCHAR NULL,
    by_laws_corporation VARCHAR NULL,
    certificate_of_good_standing_fact_status_existence VARCHAR NULL,
    city VARCHAR NULL,
    company_id VARCHAR NULL,
    company_photo VARCHAR NULL,
    company_type VARCHAR NULL,
    country VARCHAR NULL,
    ein VARCHAR NULL,
    email_address VARCHAR NULL,
    entity_type VARCHAR NULL,
    fish_id NUMERIC NULL,
    foreign_entity_registration VARCHAR NULL,
    formation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    loan VARCHAR NULL,
    name_ VARCHAR NULL,
    operating_agreement VARCHAR NULL,
    primary_contact_custom_fish_contact VARCHAR NULL,
    primary_phone VARCHAR NULL,
    property_fish_custom_property1 VARCHAR NULL,
    property VARCHAR NULL,
    related_members_shares VARCHAR NULL,
    routing_number NUMERIC NULL,
    shareholder_list_stock_certificate VARCHAR NULL,
    sole_member_llc BOOLEAN NULL,
    state_of_incorporation VARCHAR NULL,
    state_ VARCHAR NULL,
    w9_form VARCHAR NULL,
    zip VARCHAR NULL,
    created_by VARCHAR NULL,
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    modified_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);
