CREATE TABLE funding (
    unique_id VARCHAR PRIMARY KEY,
    raw_json JSON NULL,
    arbitrage VARCHAR NULL,
    archived TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    default_fee_split NUMERIC NULL,
    funded_amount NUMERIC NULL,
    funded_base NUMERIC NULL,
    funded_end_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    funded_start_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    interest_percent_of_total NUMERIC NULL,
    interest_rate_split NUMERIC NULL,
    investor_company VARCHAR NULL,
    investor_type VARCHAR NULL,
    late_payment_fee_split NUMERIC NULL,
    loan VARCHAR NULL,
    no_of_days NUMERIC NULL,
    percentage_of_loan NUMERIC NULL,
    purchase_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    source_record_id VARCHAR NULL,
    temporary TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    z_dynamics_loan VARCHAR NULL,
    created_by VARCHAR NULL,
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    modified_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);