CREATE TABLE loan (
    unique_id VARCHAR PRIMARY KEY,
    raw_json JSON,
    accrued_interest NUMERIC NULL,
    acquisition_cost NUMERIC NULL,
    additional_funds_to_close NUMERIC NULL,
    aiv_ltv NUMERIC NULL,
    amount NUMERIC NULL,
    amount_to_add NUMERIC NULL,
    amount_to_add_2 NUMERIC NULL,
    amount_to_add_3 NUMERIC NULL,
    amount_to_add_4 NUMERIC NULL,
    amount_to_add_memo VARCHAR NULL,
    amount_to_add2_memo VARCHAR NULL,
    amount_to_add3_memo VARCHAR NULL,
    amount_to_add4_memo VARCHAR NULL,
    appraisal_effective_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    arm_index NUMERIC NULL,
    arm_margin NUMERIC NULL,
    arv_ltv NUMERIC NULL,
    as_is_aiv VARCHAR NULL,
    aside_investor_legal_entity_name VARCHAR NULL,
    assignment_fee NUMERIC NULL,
    assignment_fee_credited NUMERIC NULL,
    assignment_fee_credit NUMERIC NULL,
    balloon_flag_y_n BOOLEAN NULL,
    base_interest_rate NUMERIC NULL,
    bathrooms_after_renovations NUMERIC NULL,
    bedrooms_after_renovations NUMERIC NULL,
    borrower VARCHAR NULL,
    contact_user VARCHAR NULL,
    borrower_arv NUMERIC NULL,
    borrower_as_is NUMERIC NULL,
    borrower_brings_to_closing NUMERIC NULL,
    borrower_down_payment NUMERIC NULL,
    borrower_est_repair_cost NUMERIC NULL,
    borrower_provided_arv_bath NUMERIC NULL,
    borrower_provided_arv_bed NUMERIC NULL,
    borrower_provided_arv_sqft NUMERIC NULL,
    borrower_provided_as_is_bath NUMERIC NULL,
    borrower_provided_as_is_bed NUMERIC NULL,
    borrower_provided_as_is_sqft NUMERIC NULL,
    bpo_special_instructions VARCHAR NULL,
    business_affidavit BOOLEAN NULL,
    cash_out_amount NUMERIC NULL,
    cash_out_mapped BOOLEAN NULL,
    clean_proceeds NUMERIC NULL,
    closing_conditions VARCHAR NULL,
    closing_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    closing_fee NUMERIC NULL,
    closing_instruction_letter BOOLEAN NULL,
    cltv NUMERIC NULL,
    combined_arv_ltv NUMERIC NULL,
    commercial_mixed_use_sqft_unit VARCHAR NULL,
    commercial_mixed_use_unit VARCHAR NULL,
    commercial_mixed_use_unit_mapped NUMERIC NULL,
    commitment_authorization_number VARCHAR NULL,
    commitment_fee NUMERIC NULL,
    company VARCHAR NULL,
    company_fish VARCHAR NULL,
    company_contact_merges VARCHAR NULL,
    conduit_origination_fee NUMERIC NULL,
    construction_balance NUMERIC NULL,
    construction_budget1 NUMERIC NULL,
    construction_draw_fund_balance NUMERIC NULL,
    construction_fund_amount NUMERIC NULL,
    contact VARCHAR NULL,
    contacts VARCHAR NULL,
    correspondent_price NUMERIC NULL,
    cost_basis NUMERIC NULL,
    retail_construction_amount NUMERIC NULL,
    cross_collateral_property_equity VARCHAR NULL,
    cross_collateral_property_equity_mapped NUMERIC NULL,
    current_loan_amount NUMERIC NULL,
    current_term NUMERIC NULL,
    cutoff_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    date_of_first_payment TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    days_accrued NUMERIC NULL,
    days_to_maturity NUMERIC NULL,
    days_in_year NUMERIC NULL,
    deed BOOLEAN NULL,
    default_reason VARCHAR NULL,
    disbursement_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    down_payment_source VARCHAR NULL,
    downpayment NUMERIC NULL,
    effective_ltc NUMERIC NULL,
    effective_purchase_price NUMERIC NULL,
    total_cost NUMERIC NULL,
    escrow_deposit NUMERIC NULL,
    estimated_monthly_interest_only_payment NUMERIC NULL,
    estimated_revenue NUMERIC NULL,
    existing_debt_balance NUMERIC NULL,
    expected_payoff_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    external_funding_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    feature VARCHAR NULL,
    fish_id NUMERIC NULL,
    funded_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    funding_entity_state VARCHAR NULL,
    guaranty BOOLEAN NULL,
    hoa_costs NUMERIC NULL,
    hud_interest NUMERIC NULL,
    initial_draw NUMERIC NULL,
    initial_ltc NUMERIC NULL,
    initial_rate_fixed_period NUMERIC NULL,
    insurance_premium NUMERIC NULL,
    interest_only_y_n BOOLEAN NULL,
    interest_rate NUMERIC NULL,
    interest_rate_second_trust NUMERIC NULL,
    interest_reserve NUMERIC NULL,
    interest_type VARCHAR NULL,
    intro_rate NUMERIC NULL,
    intro_terms VARCHAR NULL,
    last_sale_amount NUMERIC NULL,
    lease_amount NUMERIC NULL,
    lease_in_place BOOLEAN NULL,
    lease_term NUMERIC NULL,
    lien_amount NUMERIC NULL,
    lien_information VARCHAR NULL,
    lien_payoff_amount NUMERIC NULL,
    llc_cert BOOLEAN NULL,
    lo_arv NUMERIC NULL,
    lo_as_is NUMERIC NULL,
    lo_bath_arv NUMERIC NULL,
    lo_bath_as_is NUMERIC NULL,
    lo_beds_arv NUMERIC NULL,
    lo_beds_as_is NUMERIC NULL,
    lo_est_repair_cost NUMERIC NULL,
    lo_sqft_arv NUMERIC NULL,
    lo_sqft_as_is NUMERIC NULL,
    loan_amount NUMERIC NULL,
    loan_amount_second_trust NUMERIC NULL,
    loan_application_new VARCHAR NULL,
    loan_extensions VARCHAR NULL,
    loan_maturity_link VARCHAR NULL,
    loan_points NUMERIC NULL,
    loan_rate NUMERIC NULL,
    loan_rate_mapped NUMERIC NULL,
    loan_team VARCHAR NULL,
    loan_term NUMERIC NULL,
    loan_type VARCHAR NULL,
    ltaiv NUMERIC NULL,
    ltc NUMERIC NULL,
    ltv NUMERIC NULL,
    maturity_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    months_of_interest_reserves NUMERIC NULL,
    months_of_prepaid_interest NUMERIC NULL,
    months_remaining_io_term NUMERIC NULL,
    net_wire NUMERIC NULL,
    net_wire_interest NUMERIC NULL,
    next_due_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    note_rate NUMERIC NULL,
    number VARCHAR NULL,
    occupancy_status VARCHAR NULL,
    original_deed_of_trust BOOLEAN NULL,
    original_p_i_amount NUMERIC NULL,
    origination_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    origination_points NUMERIC NULL,
    other_closing_costs NUMERIC NULL,
    owner VARCHAR NULL,
    paid_to_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    payoff_amount NUMERIC NULL,
    payoff_approved_by_user VARCHAR NULL,
    per_diem NUMERIC NULL,
    permissions_viewable_users_list_user VARCHAR NULL,
    point_of_contact VARCHAR NULL,
    points_second_trust NUMERIC NULL,
    prepaid_interest_amount NUMERIC NULL,
    prepaid_interest_balance NUMERIC NULL,
    property_last_sold_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    primary_borrower VARCHAR NULL,
    primary_contact VARCHAR NULL,
    principal_balance NUMERIC NULL,
    proceeds NUMERIC NULL,
    process VARCHAR NULL,
    product_type VARCHAR NULL,
    loan_product VARCHAR NULL,
    property VARCHAR NULL,
    property_fish VARCHAR NULL,
    property_currently_listed VARCHAR NULL,
    property_currently_listed_mapped BOOLEAN NULL,
    property_list_price NUMERIC NULL,
    property_management_fee NUMERIC NULL,
    property_purchase_price NUMERIC NULL,
    property_taxes NUMERIC NULL,
    property_type VARCHAR NULL,
    property_valuation_comps_link VARCHAR NULL,
    rate_cap_first NUMERIC NULL,
    rate_cap_life NUMERIC NULL,
    rate_cap_periodic NUMERIC NULL,
    rate_lookback_period NUMERIC NULL,
    rate_max_life NUMERIC NULL,
    rate_min_life NUMERIC NULL,
    rate_reset_date_first TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    rate_reset_date_next TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    rate_reset_frequency NUMERIC NULL,
    rate_rounding_method NUMERIC NULL,
    rate_rounding_method_mapped VARCHAR NULL,
    referral_fee NUMERIC NULL,
    refinance_of_existing_debt BOOLEAN NULL,
    refinancing_amount NUMERIC NULL,
    related_companies VARCHAR NULL,
    released_ltv NUMERIC NULL,
    reminder_day_checked TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    remittance_account_name VARCHAR NULL,
    remittance_account_number VARCHAR NULL,
    remittance_bank_name VARCHAR NULL,
    remittance_city VARCHAR NULL,
    remittance_postal_zip_code VARCHAR NULL,
    remittance_routing_number VARCHAR NULL,
    remittance_state VARCHAR NULL,
    remittance_street_address VARCHAR NULL,
    report_type VARCHAR NULL,
    retail_construction_amount1 NUMERIC NULL,
    services VARCHAR NULL,
    servicing_fee NUMERIC NULL,
    servicing_transfer_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    settlement_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    settlement_statement_hud BOOLEAN NULL,
    source_id VARCHAR NULL,
    submission_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    subordinate_financing BOOLEAN NULL,
    summary VARCHAR NULL,
    summary_loan_app VARCHAR NULL,
    term_sheet_signed BOOLEAN NULL,
    testing BOOLEAN NULL,
    total_default_interest NUMERIC NULL,
    total_experience VARCHAR NULL,
    total_interest_paid NUMERIC NULL,
    total_loan_calculated NUMERIC NULL,
    total_ltc NUMERIC NULL,
    total_normal_interest NUMERIC NULL,
    total_project_cost NUMERIC NULL,
    total_purchase_price NUMERIC NULL,
    total_unpaid_late_fees NUMERIC NULL,
    valuation_comments VARCHAR NULL,
	valuation_fee VARCHAR NULL,
	wcp_purchase_price NUMERIC NULL,
	new_borrower_est_as_is NUMERIC NULL,
	new_requested_construction_fund_amount NUMERIC NULL,
	created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
	modified_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
	created_by VARCHAR NULL);
